module.exports = {
  User: require('./User'),
  Department: require('./Department'),
  Programme: require('./Programme'),
  Batch: require('./Batch'),
  Section: require('./Section'),
  Subject: require('./Subject'),
  AcademicTerm: require('./AcademicTerm'),
  Holiday: require('./Holiday'),
  CourseOffering: require('./CourseOffering'),
  ClassSession: require('./ClassSession'),
  AttendanceRecord: require('./AttendanceRecord'),
  AttendanceSummary: require('./AttendanceSummary'),
  CorrectionRequest: require('./CorrectionRequest'),
  LeaveRequest: require('./LeaveRequest'),
  ExportTemplate: require('./ExportTemplate'),
  AuditLog: require('./AuditLog'),
  Notification: require('./Notification'),
  Counter: require('./Counter'),
};
